server:
  port: 9000

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: theinlwin
    key-pair-alias: mytestkey
    key-pair-password: finderbar

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/views/
    suffix: .html